// <auto-generated />
using System;
using System.Collections.Generic;
using Finansium.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finansium.Persistence.Migrations
{
    [DbContext(typeof(FinansiumDbContext))]
    [Migration("20241025181946_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finansium.Domain.Accounts.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.ComplexProperty<Dictionary<string, object>>("Balance", "Finansium.Domain.Accounts.Account.Balance#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("balance_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("balance_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_accounts_user_id");

                    b.ToTable("accounts", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Accounts.AccountTransfer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<decimal>("CurrencyRate")
                        .HasColumnType("numeric")
                        .HasColumnName("currency_rate");

                    b.Property<DateTimeOffset>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SourceAccountId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("source_account_id");

                    b.Property<string>("TargetAccountId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("target_account_id");

                    b.HasKey("Id")
                        .HasName("pk_account_transfers");

                    b.HasIndex("SourceAccountId")
                        .HasDatabaseName("ix_account_transfers_source_account_id");

                    b.HasIndex("TargetAccountId")
                        .HasDatabaseName("ix_account_transfers_target_account_id");

                    b.ToTable("account_transfers", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Budgets.Budget", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("category_id");

                    b.Property<decimal>("LimitAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("limit_amount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_budgets_category_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_budgets_type");

                    b.ToTable("budgets", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Categories.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("BudgetId")
                        .HasColumnType("text")
                        .HasColumnName("budget_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("transaction_type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("TransactionType")
                        .HasDatabaseName("ix_categories_transaction_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_categories_user_id");

                    b.ToTable("categories", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Counties.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("alpha2code");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("alpha3code");

                    b.Property<string>("FullName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("full_name");

                    b.Property<short>("NumericCode")
                        .HasColumnType("smallint")
                        .HasColumnName("numeric_code");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("short_name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("Alpha2Code")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_alpha2code");

                    b.HasIndex("Alpha3Code")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_alpha3code");

                    b.HasIndex("NumericCode")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_numeric_code");

                    b.HasIndex("ShortName")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_short_name");

                    b.ToTable("countries", "core");
                });

            modelBuilder.Entity("Finansium.Domain.News.NewsItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsOutdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_outdated");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news_items");

                    b.ToTable("news_items", "core");
                });

            modelBuilder.Entity("Finansium.Domain.OutboxMessages.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "core");
                });

            modelBuilder.Entity("Finansium.Domain.RecurringTransactions.RecurringTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("interval")
                        .HasColumnName("interval");

                    b.Property<DateTimeOffset?>("NextPaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_payment_date");

                    b.Property<DateTimeOffset>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_recurring_transactions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_recurring_transactions_account_id");

                    b.ToTable("recurring_transactions", "core");
                });

            modelBuilder.Entity("Finansium.Domain.SavingsGoals.SavingsGoal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<DateTimeOffset>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_savings_goals");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_savings_goals_account_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_savings_goals_user_id");

                    b.ToTable("savings_goals", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("ExpiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("StartAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_subscriptions_user_id");

                    b.ToTable("subscriptions", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Transactions.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("account_id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_transactions_account_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.ToTable("transactions", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Users.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsViewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_viewed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Users.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_permissions_role_id");

                    b.ToTable("permissions", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Users.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("ExpiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("StartAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)")
                        .HasColumnName("token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Users.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("country_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(97)
                        .HasColumnType("character varying(97)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_users_country_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", "core");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("roles_id");

                    b.Property<string>("UsersId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("pk_role_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_role_user_users_id");

                    b.ToTable("role_user", "core");
                });

            modelBuilder.Entity("Finansium.Domain.Accounts.Account", b =>
                {
                    b.HasOne("Finansium.Domain.Users.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finansium.Domain.Accounts.AccountTransfer", b =>
                {
                    b.HasOne("Finansium.Domain.Accounts.Account", "SourceAccount")
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_transfers_accounts_source_account_id");

                    b.HasOne("Finansium.Domain.Accounts.Account", "TargetAccount")
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_transfers_accounts_target_account_id");

                    b.OwnsOne("Finansium.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<string>("AccountTransferId")
                                .HasColumnType("character varying(26)")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("amount_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.HasKey("AccountTransferId");

                            b1.ToTable("account_transfers", "core");

                            b1.WithOwner()
                                .HasForeignKey("AccountTransferId")
                                .HasConstraintName("fk_account_transfers_account_transfers_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("SourceAccount");

                    b.Navigation("TargetAccount");
                });

            modelBuilder.Entity("Finansium.Domain.Budgets.Budget", b =>
                {
                    b.HasOne("Finansium.Domain.Categories.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Finansium.Domain.Categories.Category", b =>
                {
                    b.HasOne("Finansium.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finansium.Domain.RecurringTransactions.RecurringTransaction", b =>
                {
                    b.HasOne("Finansium.Domain.Accounts.Account", "Account")
                        .WithMany("RecurringTransactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_transactions_accounts_account_id");

                    b.OwnsOne("Finansium.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<string>("RecurringTransactionId")
                                .HasColumnType("character varying(26)")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("amount_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.HasKey("RecurringTransactionId");

                            b1.ToTable("recurring_transactions", "core");

                            b1.WithOwner()
                                .HasForeignKey("RecurringTransactionId")
                                .HasConstraintName("fk_recurring_transactions_recurring_transactions_id");
                        });

                    b.Navigation("Account");

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Finansium.Domain.SavingsGoals.SavingsGoal", b =>
                {
                    b.HasOne("Finansium.Domain.Accounts.Account", "Account")
                        .WithMany("SavingsGoals")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_savings_goals_accounts_account_id");

                    b.HasOne("Finansium.Domain.Users.User", null)
                        .WithMany("SavingsGoals")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_savings_goals_users_user_id");

                    b.OwnsOne("Finansium.Domain.Shared.Money", "TargetAmount", b1 =>
                        {
                            b1.Property<string>("SavingsGoalId")
                                .HasColumnType("character varying(26)")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("target_amount_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("target_amount_currency");

                            b1.HasKey("SavingsGoalId");

                            b1.ToTable("savings_goals", "core");

                            b1.WithOwner()
                                .HasForeignKey("SavingsGoalId")
                                .HasConstraintName("fk_savings_goals_savings_goals_id");
                        });

                    b.Navigation("Account");

                    b.Navigation("TargetAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("Finansium.Domain.Subscriptions.Subscription", b =>
                {
                    b.HasOne("Finansium.Domain.Users.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finansium.Domain.Transactions.Transaction", b =>
                {
                    b.HasOne("Finansium.Domain.Accounts.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_accounts_account_id");

                    b.HasOne("Finansium.Domain.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_categories_category_id");

                    b.OwnsOne("Finansium.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<string>("TransactionId")
                                .HasColumnType("character varying(26)")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("amount_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transactions", "core");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId")
                                .HasConstraintName("fk_transactions_transactions_id");
                        });

                    b.Navigation("Account");

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Finansium.Domain.Users.Notification", b =>
                {
                    b.HasOne("Finansium.Domain.Users.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finansium.Domain.Users.Permission", b =>
                {
                    b.HasOne("Finansium.Domain.Users.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permissions_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Finansium.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("Finansium.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finansium.Domain.Users.User", b =>
                {
                    b.HasOne("Finansium.Domain.Counties.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_countries_country_id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Finansium.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_roles_roles_id");

                    b.HasOne("Finansium.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_users_users_id");
                });

            modelBuilder.Entity("Finansium.Domain.Accounts.Account", b =>
                {
                    b.Navigation("RecurringTransactions");

                    b.Navigation("SavingsGoals");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finansium.Domain.Categories.Category", b =>
                {
                    b.Navigation("Budgets");
                });

            modelBuilder.Entity("Finansium.Domain.Users.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Finansium.Domain.Users.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Notifications");

                    b.Navigation("SavingsGoals");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
